#!/bin/bash
# Keycloak master realm에 admin 사용자 생성 스크립트

echo "=== Keycloak Admin 사용자 설정 ==="
echo ""
echo "Keycloak의 master realm에 admin 사용자가 없습니다."
echo ""
echo "해결 방법:"
echo "1. 브라우저에서 http://localhost:8080 접속"
echo "2. 'Administration Console' 클릭"
echo "3. Username: admin, Password: admin으로 로그인"
echo "4. master realm 선택 (왼쪽 상단)"
echo "5. Users → Create new user 클릭"
echo "6. Username: admin 입력"
echo "7. Enabled: ON 체크"
echo "8. Create 클릭"
echo "9. Credentials 탭 클릭"
echo "10. Password와 Password confirmation에 'admin' 입력"
echo "11. Temporary: OFF로 설정"
echo "12. Set password 클릭"
echo ""
echo "또는 다음 명령어로 테스트할 수 있습니다:"
echo ""
echo "# my-realm 사용 (이미 설정된 경우)"
echo "curl -X POST \"http://localhost:8080/realms/my-realm/protocol/openid-connect/token\" \\"
echo "  -H \"Content-Type: application/x-www-form-urlencoded\" \\"
echo "  -d \"client_id=backend-client\" \\"
echo "  -d \"grant_type=password\" \\"
echo "  -d \"username=testuser\" \\"
echo "  -d \"password=testuser\""
echo ""
